### ISSUE TITLE
Confused. :)

### ISSUE THREAD

**Issue by Mike-E-angelo** [bgrainger/InPerformance#1]
First off, thank you for your informative article!  I very much appreciate you taking the time to write and to provide the code here.

I myself have found confusing results in my scenario so that is why I started to search online and found your article.

I do see that you are padding your structs and do make note of this in your article.  However, when I do remove that padding, I get some pretty unexpected results:

```
               Method |     Mean |     Error |    StdDev | Allocated |
--------------------- |---------:|----------:|----------:|----------:|
         PointByValue | 2.496 ns | 0.0130 ns | 0.0115 ns |       0 B |
           PointByRef | 8.189 ns | 0.1369 ns | 0.1214 ns |       0 B |
            PointByIn | 8.981 ns | 0.2041 ns | 0.1809 ns |       0 B |
 ReadOnlyPointByValue | 2.526 ns | 0.1278 ns | 0.1067 ns |       0 B |
   ReadOnlyPointByRef | 8.796 ns | 0.1608 ns | 0.1504 ns |       0 B |
    ReadOnlyPointByIn | 8.512 ns | 0.0383 ns | 0.0320 ns |       0 B |
```

In my case I am also seeing better results without using `in`.  So it makes me wonder, is this really only valuable if you are using extra large structs?

Thank you for any insight you can provide.

**Comment by bgrainger** [comment]
I updated my test app to `netcoreapp2.1` and saw even worse performance than you reported:

Method |      Mean |     Error |    StdDev |
--------------------- |----------:|----------:|----------:|
PointByValue |  2.077 ns | 0.0461 ns | 0.0431 ns |
PointByRef |  9.580 ns | 0.1358 ns | 0.1270 ns |
PointByIn | 13.399 ns | 0.1046 ns | 0.0978 ns |
ReadOnlyPointByValue |  2.086 ns | 0.0342 ns | 0.0303 ns |
ReadOnlyPointByRef |  9.700 ns | 0.1144 ns | 0.1070 ns |
ReadOnlyPointByIn |  9.641 ns | 0.1476 ns | 0.1380 ns |

I also note that `ByRef` is significantly worse, when it used to be the fastest approach. This may need further investigation.

**Comment by bgrainger** [comment]
Based on [SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQFEAeAHJzkCWA9gHYBqUCBUwANigDQwhTIC2APgAIAMABFwCMAbgCwAKACQXAMx9kMBHADGMPgAUiBEjBkARCZIDeh6XM3bdegBQATInDoQ+mBn3uP6fAJ5uPTvgAvAEpTEylJSQANPgBeFzEIyQBNOJ9EyMkALTTAjMkAXwlTWXcHAJijPgBzCBhhPiKI0v8vVKra+saSuVbnHI66hqbCiVKuACY+AGE+cMiW8q8LHQAhbwpaOAhrUIj5yL6+PQIFKBJlHZWrPig3a/0+YD3Mg8iAN0oXNKgAOhjUE9/vkPl9vD9fqlAcBISDJJ8EEEITlob8snCuAB2PgAWVgAAtfgBlACOCBg1kwfAAVN8ANQ+GmMhmBJkhEFNUzwr7YQRpEgQADuGi0On01kEbklfEEwRBCL42Cm8QFwoeNgmbk1fAmcq5WOOpxg50u1l5biVeoinIiAHpbTrBL8ABwkZA9MqeZzXdYAJQgYF2YS5RxOZwuOyQYBFlkedz4UZjYr0TxekTe3MRVPifwBQKicIV4JzkL4qOSha+rJLKKB6K50mxeJghNJ5MpTKpDPBtPBLLZVsyNsyCt5/KFSasEqlUsHoMRSvHatFU+1a7njcN4dNifNCYDit1+WHkntfBkABZfgA2N0eo4+7wASRIQf2IaWzjDxoj1m0k7jNx/3VVMuQzBVs1uf4y3zStEWLKCoSBCsGwVasoNrGF6ySTdm1bMkKSpWku0ZXs+H7Wl2S5E9M0VPkVQndVpxlWd5R5ZU+FVACNS1LUNwNb8TR2f89xEo9TCaAogA) it appears that when `Point3D` is small enough to fit within the CPU registers, `PointByValue` just inlines the call to `Distance`. I had to add sufficient padding that each method actually made a function call (and passed the `Point3D` by value or by reference, etc.) to have a "fair" comparison. `ByValue` "should" be about the same speed as `ByRef`, but extra JIT optimisations kick in here to make it a lot faster. (The overhead of the function call has now become the dominating factor.)

So this is just a reminder that you should always [benchmark your specific scenario](https://ericlippert.com/2012/12/17/performance-rant/) instead of relying on some random guy on the Internet's results. 😀

**Comment by Mike-E-angelo** [comment]
Ok cool!  Sanity (somewhat) restored. 😆  Thank you for taking the time to answer and provide more context!

That link is good advice indeed.  I should follow it sometime. 😇
